version: "2"
services:

  db:
    image: mysql:8
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      db:
         condition: service_healthy