---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}.auth
type: Opaque
data:
  token: {{ .Values.secret.token | b64enc }}
  authorization: {{ .Values.secret.authorization | b64enc }}
